on:
  pull_request:
    branches:
      - main
      - master
      - new-ui
  push:
    branches:
      - main
      - master
      - develop
      - new-ui

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - run: flutter build windows --release
      - run: flutter build linux --release
      - run: flutter build macos --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/runner/Release/*.exe, build/linux/x64/release/*.AppImage, build/macos/Build/Products/Release/*.app"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
# push to master, main, develop
# pull request on main master
